### ISSUE TITLE
using release 0.0.2 - fails to create new container

### ISSUE THREAD

**Issue by bmullan** [bketelsen/lxdev#10]
finally found out about the 0.0.2 release and downloaded it.

I tried to copy your video and got to creating a new container and it failed.

> $ lxdev create newcn
> ~ Creating container newcn
> ✗ Unable to create container: creating container: Must specify one of alias, fingerprint or properties for init from image

I am on ubuntu 18.04 and using SNAP LXD

**Comment by bmullan** [comment]
Ok... just did this.. using release 0.0.2

$ lxdev config -c
~ Create configuration
✓ Default configuration file created
✓ Configuration created
bmullan@dadspc:/etc/pulse$ lxdev config -t
~ Create configuration
✓ Templates created
✓ Configuration created
bmullan@dadspc:/etc/pulse$ lxdev template create goapps --profile gui --provisioners yadm,vscode
~ Creating template goapps
✗ Unable to create template: wait for create container: Create container: Requested profile 'gui' doesn't exis

**Comment by bmullan** [comment]
I am using SNAP version of LXD if that makes a difference

**Comment by bketelsen** [comment]
made new release 0.0.3
