### ISSUE TITLE
permissions problem - lxdev template create clitemplate --profile cli --provisioners go,yadm

### ISSUE THREAD

**Issue by bmullan** [bketelsen/lxdev#15]
When executing:
lxdev template create clitemplate --profile cli --provisioners go,yadm

eventually see the following:

> Initialized empty shared Git repository in /home/ubuntu/.yadm/repo.git/
> The authenticity of host 'github.com (192.30.253.112)' can't be established.
> RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
> Are you sure you want to continue connecting (yes/no)? yes
> Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
> git@github.com: Permission denied (publickey).
> **fatal: Could not read from remote repository.**
> 
> **Please make sure you have the correct access rights**
> and the repository exists.
> **ERROR: Unable to fetch origin git@github.com:bketelsen/dotfiles**

**Comment by bketelsen** [comment]
yes, that's to be expected, you want to edit ~/.lxdev/provision/yadm.sh to bootstrap YOUR dotfiles.  Right now it's expecting to have my ssh keys and do an authenticated git clone, which isn't going to work for you.

Better yet, create your own dotfile provisioner based on how you would normally get your dotfiles on a new dev machine, place it in the ~/.lxdev/provision directory, then add it to the `--provisioners` argument.

**Comment by bketelsen** [comment]
@bmullan would you like to do a zoom meeting/screen share so I can walk you through the internals and assumptions that `lxdev` makes?  I suspect your frustrations could be avoided in the future with better documentation and a better "first-run" user experience.  I'd love your input on that.

**Comment by bmullan** [comment]
sure... I haven't heard of zoom meeting so I'd have to look up how to
use/do it first.

brian
