### ISSUE TITLE
Name collision with other project

### ISSUE THREAD

**Issue by sokkalf** [bketelsen/lxdev#22]
Hi,

We (some colleagues and I) have been working on a similar project for some time.
https://github.com/GyldendalDigital/lxdev

 Just found your project, and I see it has the exact same name and overlapping features. Any chance you could consider calling it something else?

**Comment by bketelsen** [comment]
@sokkalf wow that's really neat!  Can't wait to investigate your 'lxdev'.  Yes, I'll rename this shortly to avoid confusion.
