### ISSUE TITLE
make deps fail 

### ISSUE THREAD

**Issue by ChristianBoehm** [bketelsen/lxdev#6]
Dear Brian,

make deps fail with error message: cannot load github.com/bketelsen/libgo/events
if I try to curl your url on github (github.com/bketelsen/libgo/events) I got a 404 error

**Comment by bketelsen** [comment]
hmm, maybe I should release that!

**Comment by ChristianBoehm** [comment]
that's would be nice and I'll could continue testing

**Comment by bketelsen** [comment]
done, sorry about that.

**Comment by bketelsen** [comment]
I'll test again locally in a moment, the repo was private and I didn't notice  :/

**Comment by ChristianBoehm** [comment]
That's what I thought, but I was not sure ;) and I didn't notice that there is a release available for download. Maybe a link on README.md could make sense? In the meanwhile I'll be doing some tests with the binary release and let you know if it works. Thanks for supporting

**Comment by ChristianBoehm** [comment]
Building from sources is now working like a charm. Thanks for open your private repo. Therefore I can close here. Thank you
